[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pydantic = "^2.10.5"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
